/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package information.system.project;

/**
 *
 * @author YOUSSEF
 */
public class monitorSelectPage extends javax.swing.JFrame {

    /**
     * Creates new form monitorSelectPage
     */
    public monitorSelectPage() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cc1600 = new javax.swing.JRadioButton();
        cc1800 = new javax.swing.JRadioButton();
        cc2000 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/information/system/project/monitorselect.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        cc1600.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        cc1600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cc1600ActionPerformed(evt);
            }
        });
        getContentPane().add(cc1600);
        cc1600.setBounds(680, 190, 590, 100);

        cc1800.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        cc1800.setText("jRadioButton2");
        getContentPane().add(cc1800);
        cc1800.setBounds(690, 430, 590, 110);

        cc2000.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        getContentPane().add(cc2000);
        cc2000.setBounds(710, 650, 580, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cc1600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cc1600ActionPerformed
        
    }//GEN-LAST:event_cc1600ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(monitorSelectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(monitorSelectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(monitorSelectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(monitorSelectPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new monitorSelectPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cc1600;
    private javax.swing.JRadioButton cc1800;
    private javax.swing.JRadioButton cc2000;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
